version: "3"
services:
  node-web-app:
    working_dir: /usr/app
    build: .
    restart: always
    depends_on:
      - postgres
    expose:
      - 4000
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/usr/app/src:rw
      - ./logs:/root/.npm/_logs/
    networks:
      - trier_1

  postgres:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/logs
    networks:
      - trier_1

networks:
  trier_1: {}